# Data Preparation

In [ ]:
import numpy as np
import pandas as pd
import yfinance as yf
from market_ml.data_loader import DataLoader
import matplotlib.pyplot as plt
from market_ml.config import *

Downloading the SPY Data

In [ ]:
tickers = TICKERS
sector_map = TICKER_SECTOR

test_tickers = tickers[0:4]

test_tickers

['AAPL', 'MSFT', 'NVDA', 'META']

In [ ]:
DL = DataLoader(tickers=test_tickers, period="10y", interval="1d")

raw_data = DL.download_data()

processed_data = DL.process_data(raw_data)
processed_validation = DL.check_data(processed_data, ticker_summary=True)
print(processed_validation)
#DL.save_data()

[*********************100%***********************]  4 of 4 completed

Downloaded data for ['AAPL', 'MSFT', 'NVDA', 'META']
Processed data for ['AAPL', 'MSFT', 'NVDA', 'META']
DATA VALIDATION:
--------------------------------------------------------------------------------
Missing Values: 0
Number of Rows: 10056
Number of Columns: 8
Start: 0
End: 10055
Duplicate Rows: 0
Duplicate Date/Ticker: 0
ticker_validation

        Rows      Start        End  Missing_Close
Ticker
AAPL    2514 2016-09-26 2026-09-25              0
META    2514 2016-09-26 2026-09-25              0
MSFT    2514 2016-09-26 2026-09-25              0
NVDA    2514 2016-09-26 2026-09-25              0

None

In [ ]:
DL.data

Price,Date,Ticker,Sector,Close,High,Low,Open,Volume
0,2016-09-26,AAPL,Technology,25.814035,25.930666,25.509885,25.530466,119477600
1,2016-09-26,META,Technology,126.102226,126.944168,125.597070,126.161662,15064900
2,2016-09-26,MSFT,Technology,50.525341,50.738451,50.463184,50.685175,21688700
3,2016-09-26,NVDA,Technology,1.578443,1.584822,1.558572,1.575254,230040000
4,2016-09-27,AAPL,Technology,25.862059,25.882641,25.690544,25.841478,98429600
...,...,...,...,...,...,...,...,...
10051,2026-09-24,NVDA,Technology,224.580002,224.940002,221.089996,222.080002,77305200
10052,2026-09-25,AAPL,Technology,339.320007,339.350006,334.529999,336.040009,8912672
10053,2026-09-25,META,Technology,749.844971,769.570007,746.540527,768.844971,13273406
10054,2026-09-25,MSFT,Technology,514.385010,517.479980,497.299988,499.140015,17586890
10055,2026-09-25,NVDA,Technology,224.810104,226.940002,223.132904,225.149994,34828749