# Data Preparation

In [5]:
import numpy as np
import pandas as pd
import yfinance as yf
from market_ml.data_loader import DataLoader
import matplotlib.pyplot as plt
from market_ml.config import * #

Downloading the Data

In [6]:
TICKERS

['AAPL',
 'MSFT',
 'NVDA',
 'META',
 'GOOGL',
 'JPM',
 'GS',
 'BAC',
 'MS',
 'BLK',
 'JNJ',
 'UNH',
 'ABBV',
 'PFE',
 'MRK',
 'XOM',
 'CVX',
 'COP',
 'SLB',
 'EOG',
 'AMZN',
 'COST',
 'WMT',
 'HD',
 'MCD']

In [13]:
stock_dl = DataLoader(tickers=TICKERS, period="10y", interval="1d", file_name="stock_data.parquet")
benchmark_dl = DataLoader(tickers=BENCHMARK_TICKERS, period="10y", interval="1d", file_name="benchmark_data.parquet")

In [14]:
raw_stock_data = stock_dl.download_data()
raw_benchmark_data = benchmark_dl.download_data()

[*********************100%***********************]  25 of 25 completed

Downloaded data for ['AAPL', 'MSFT', 'NVDA', 'META', 'GOOGL', 'JPM', 'GS', 'BAC', 'MS', 'BLK', 'JNJ', 'UNH', 'ABBV', 'PFE', 'MRK', 'XOM', 'CVX', 'COP', 'SLB', 'EOG', 'AMZN', 'COST', 'WMT', 'HD', 'MCD']

[*********************100%***********************]  2 of 2 completed

Downloaded data for ['SPY', 'QQQ']

In [15]:
processed_stock_data = stock_dl.process_data(raw_stock_data)
processed_benchmark_data = benchmark_dl.process_data(raw_benchmark_data)

Processed data for ['AAPL', 'MSFT', 'NVDA', 'META', 'GOOGL', 'JPM', 'GS', 'BAC', 'MS', 'BLK', 'JNJ', 'UNH', 'ABBV', 'PFE', 'MRK', 'XOM', 'CVX', 'COP', 'SLB', 'EOG', 'AMZN', 'COST', 'WMT', 'HD', 'MCD']
Processed data for ['SPY', 'QQQ']

In [17]:
processed_stock_validation = stock_dl.check_data(processed_stock_data)

processed_stock_validation

        Rows      Start        End  Missing_Close
Ticker
AAPL    2513 2016-09-29 2026-09-29              0
ABBV    2513 2016-09-29 2026-09-29              0
AMZN    2513 2016-09-29 2026-09-29              0
BAC     2513 2016-09-29 2026-09-29              0
BLK     2513 2016-09-29 2026-09-29              0
COP     2513 2016-09-29 2026-09-29              0
COST    2513 2016-09-29 2026-09-29              0
CVX     2513 2016-09-29 2026-09-29              0
EOG     2513 2016-09-29 2026-09-29              0
GOOGL   2513 2016-09-29 2026-09-29              0
GS      2513 2016-09-29 2026-09-29              0
HD      2513 2016-09-29 2026-09-29              0
JNJ     2513 2016-09-29 2026-09-29              0
JPM     2513 2016-09-29 2026-09-29              0
MCD     2513 2016-09-29 2026-09-29              0
META    2513 2016-09-29 2026-09-29              0
MRK     2513 2016-09-29 2026-09-29              0
MS      2513 2016-09-29 2026-09-29              0
MSFT    2513 2016-09-29 2026-09-29              0
NVDA    2513 2016-09-29 2026-09-29              0
PFE     2513 2016-09-29 2026-09-29              0
SLB     2513 2016-09-29 2026-09-29              0
UNH     2513 2016-09-29 2026-09-29              0
WMT     2513 2016-09-29 2026-09-29              0
XOM     2513 2016-09-29 2026-09-29              0

In [18]:
processed_benchmark_validation = benchmark_dl.check_data(processed_benchmark_data)

processed_benchmark_validation

        Rows      Start        End  Missing_Close
Ticker
QQQ     2513 2016-09-29 2026-09-29              0
SPY     2513 2016-09-29 2026-09-29              0

Saving the Data if happy with the validation

In [19]:
stock_dl.save_data()
benchmark_dl.save_data()

Process data saved for ['AAPL', 'MSFT', 'NVDA', 'META', 'GOOGL', 'JPM', 'GS', 'BAC', 'MS', 'BLK', 'JNJ', 'UNH', 'ABBV', 'PFE', 'MRK', 'XOM', 'CVX', 'COP', 'SLB', 'EOG', 'AMZN', 'COST', 'WMT', 'HD', 'MCD']
Process data saved for ['SPY', 'QQQ']

Loading the data

In [21]:
market_data = stock_dl.load_data()

Data loaded for ['AAPL', 'MSFT', 'NVDA', 'META', 'GOOGL', 'JPM', 'GS', 'BAC', 'MS', 'BLK', 'JNJ', 'UNH', 'ABBV', 'PFE', 'MRK', 'XOM', 'CVX', 'COP', 'SLB', 'EOG', 'AMZN', 'COST', 'WMT', 'HD', 'MCD']

In [22]:
benchmark_data = benchmark_dl.load_data()

Data loaded for ['SPY', 'QQQ']