# Feature Engineering

In [1]:
import numpy as np
import pandas as pd
import yfinance as yf
from market_ml.data_loader import DataLoader
import matplotlib.pyplot as plt
import plotly.express as px
from market_ml.config import * 
from market_ml.EDA import * 
from market_ml.feature_engineering import *

# Data Loading

In [2]:
stock_dl = DataLoader(tickers=TICKERS, period="10y", interval="1d", file_name='stock_data.parquet')
benchmark_dl = DataLoader(tickers=[BENCHMARK_TICKERS], period="10y", interval="1d", file_name='benchmark_data.parquet')

market_data = stock_dl.load_data()
benchmark_data = benchmark_dl.load_data()
sectors = market_data["Sector"].unique()

benchmark_data

Data loaded for ['AAPL', 'MSFT', 'NVDA', 'META', 'GOOGL', 'JPM', 'GS', 'BAC', 'MS', 'BLK', 'JNJ', 'UNH', 'ABBV', 'PFE', 'MRK', 'XOM', 'CVX', 'COP', 'SLB', 'EOG', 'AMZN', 'COST', 'WMT', 'HD', 'MCD']
Data loaded for [['SPY', 'QQQ']]

Price,Date,Ticker,Sector,Close,High,Low,Open,Volume
0,2016-09-29,QQQ,NaN,110.121559,110.943924,109.644969,110.738333,27207500
1,2016-09-29,SPY,NaN,183.335754,185.206007,182.789198,184.804628,128070600
2,2016-09-30,QQQ,NaN,110.943939,111.271013,110.299131,110.411274,25543200
3,2016-09-30,SPY,NaN,184.719223,185.419493,183.916465,184.164118,117202900
4,2016-10-03,QQQ,NaN,110.785042,110.925211,110.355165,110.803729,19216400
...,...,...,...,...,...,...,...,...
5021,2026-09-25,SPY,NaN,771.349976,772.280029,766.289978,768.780029,36666700
5022,2026-09-28,QQQ,NaN,736.530029,741.419983,731.630005,740.460022,41716200
5023,2026-09-28,SPY,NaN,765.609985,769.539978,763.719971,768.349976,42296700
5024,2026-09-29,QQQ,NaN,737.229980,740.579895,736.000000,740.169983,9703756
5025,2026-09-29,SPY,NaN,763.820007,766.950012,762.570007,766.830017,11943944

In [3]:
#just testing with one stock for now 

test_ticker = ['AAPL', 'NVDA']
test_data = market_data[market_data["Ticker"].isin(test_ticker)].copy()

test_data

Price,Date,Ticker,Sector,Close,High,Low,Open,Volume
0,2016-09-29,AAPL,Technology,25.653965,26.024437,25.567065,25.878078,143548000
19,2016-09-29,NVDA,Technology,1.653514,1.658666,1.620394,1.635605,336684000
25,2016-09-30,AAPL,Technology,25.852909,25.926088,25.567052,25.717984,145516400
44,2016-09-30,NVDA,Technology,1.680990,1.697427,1.652778,1.662591,429932000
50,2016-10-03,AAPL,Technology,25.731701,25.852906,25.676817,25.775152,86807200
...,...,...,...,...,...,...,...,...
62769,2026-09-25,NVDA,Technology,225.070007,226.940002,223.130005,225.130005,89947700
62775,2026-09-28,AAPL,Technology,338.399994,342.989990,338.040009,340.369995,32724700
62794,2026-09-28,NVDA,Technology,228.860001,233.210007,228.039993,229.750000,141544300
62800,2026-09-29,AAPL,Technology,332.345001,337.059998,331.510010,337.059998,12025955
62819,2026-09-29,NVDA,Technology,230.899994,232.820007,229.220001,230.994995,40270708

In [4]:
FE = FeatureEngineer(test_data, benchmark_data, filename="test_stock_data_with_features.parquet")

FE.data

Price,Date,Ticker,Sector,Close,High,Low,Open,Volume
0,2016-09-29,AAPL,Technology,25.653965,26.024437,25.567065,25.878078,143548000
19,2016-09-29,NVDA,Technology,1.653514,1.658666,1.620394,1.635605,336684000
25,2016-09-30,AAPL,Technology,25.852909,25.926088,25.567052,25.717984,145516400
44,2016-09-30,NVDA,Technology,1.680990,1.697427,1.652778,1.662591,429932000
50,2016-10-03,AAPL,Technology,25.731701,25.852906,25.676817,25.775152,86807200
...,...,...,...,...,...,...,...,...
62769,2026-09-25,NVDA,Technology,225.070007,226.940002,223.130005,225.130005,89947700
62775,2026-09-28,AAPL,Technology,338.399994,342.989990,338.040009,340.369995,32724700
62794,2026-09-28,NVDA,Technology,228.860001,233.210007,228.039993,229.750000,141544300
62800,2026-09-29,AAPL,Technology,332.345001,337.059998,331.510010,337.059998,12025955
62819,2026-09-29,NVDA,Technology,230.899994,232.820007,229.220001,230.994995,40270708

Benchmark Features

In [5]:
list(benchmark_data["Ticker"].unique())

['QQQ', 'SPY']

# Returns for the benchmark

In [6]:

test_data = FE.add_benchmark_returns()
test_data

Price,Date,Ticker,Sector,Close,High,Low,Open,Volume,QQQ_Return,SPY_Return
0,2016-09-29,AAPL,Technology,25.653965,26.024437,25.567065,25.878078,143548000,NaN,NaN
1,2016-09-29,NVDA,Technology,1.653514,1.658666,1.620394,1.635605,336684000,NaN,NaN
2,2016-09-30,AAPL,Technology,25.852909,25.926088,25.567052,25.717984,145516400,0.007468,0.007546
3,2016-09-30,NVDA,Technology,1.680990,1.697427,1.652778,1.662591,429932000,0.007468,0.007546
4,2016-10-03,AAPL,Technology,25.731701,25.852906,25.676817,25.775152,86807200,-0.001432,-0.002404
...,...,...,...,...,...,...,...,...,...,...
5021,2026-09-25,NVDA,Technology,225.070007,226.940002,223.130005,225.130005,89947700,0.004588,0.005435
5022,2026-09-28,AAPL,Technology,338.399994,342.989990,338.040009,340.369995,32724700,-0.010705,-0.007441
5023,2026-09-28,NVDA,Technology,228.860001,233.210007,228.039993,229.750000,141544300,-0.010705,-0.007441
5024,2026-09-29,AAPL,Technology,332.345001,337.059998,331.510010,337.059998,12025955,0.000950,-0.002338
5025,2026-09-29,NVDA,Technology,230.899994,232.820007,229.220001,230.994995,40270708,0.000950,-0.002338

# Returns

In [7]:

test_data = FE.add_daily_returns() #Daily Price Movement 
test_data = FE.add_return_feature() #Very short term momentum - default is 5 days.

# Volatility Features

In [8]:

test_data = FE.add_volatility_feature() #recent variability - default is 20 days

# Trend Features

In [9]:
test_data = FE.add_SMA_feature() #recent price trend - default is 20 
test_data = FE.add_SMA_feature(50) #longer term price trend 
test_data = FE.add_price_relative_to_sma() #position relative to trend - default is 20
test_data = FE.add_price_relative_to_sma(50) #position relative to longer trend 

test_data.tail(20)

Price,Date,Ticker,Sector,Close,High,Low,Open,Volume,QQQ_Return,SPY_Return,Daily_Return,Return_5D,Volatility_20D,SMA_20D,SMA_50D,Price_to_SMA_20D,Price_to_SMA_50D
5006,2026-09-16,AAPL,Technology,332.410004,335.480011,330.700012,332.529999,35981000,0.000255,-0.004410,0.003229,0.054132,0.014942,320.389998,319.144035,1.037517,1.041567
5007,2026-09-16,NVDA,Technology,213.899994,216.759995,212.500000,214.139999,96563600,0.000255,-0.004410,0.008154,-0.042610,0.028648,218.334263,213.363682,0.979690,1.002514
5008,2026-09-17,AAPL,Technology,337.000000,338.339996,330.179993,334.769989,36700200,0.017312,0.011339,0.013808,0.031938,0.014522,321.398499,319.621636,1.048543,1.054372
5009,2026-09-17,NVDA,Technology,219.339996,219.910004,217.149994,218.380005,94191300,0.017312,0.011339,0.025432,0.004488,0.029149,218.435421,213.672645,1.004141,1.026524
5010,2026-09-18,AAPL,Technology,336.130005,338.489990,332.529999,337.910004,86588200,0.006319,0.001287,-0.002582,0.011617,0.013771,322.639999,320.025286,1.041811,1.050323
5011,2026-09-18,NVDA,Technology,222.270004,222.729996,218.029999,219.350006,190287400,0.006319,0.001287,0.013358,0.018233,0.029262,218.718539,214.066978,1.016238,1.038320
5012,2026-09-21,AAPL,Technology,338.980011,339.640015,333.049988,335.279999,34999200,0.028821,0.015505,0.008479,0.017714,0.013590,324.121500,320.503920,1.045842,1.057647
5013,2026-09-21,NVDA,Technology,227.380005,228.500000,221.559998,222.940002,109806100,0.028821,0.015505,0.022990,0.077835,0.029501,219.363539,214.400094,1.036544,1.060541
5014,2026-09-22,AAPL,Technology,339.750000,345.339996,338.750000,340.140015,40711800,0.008079,-0.000155,0.002271,0.025382,0.013596,325.592000,320.958188,1.043484,1.058549
5015,2026-09-22,NVDA,Technology,228.869995,229.979996,226.500000,226.850006,95746700,0.008079,-0.000155,0.006553,0.078710,0.028501,220.394690,214.911444,1.038455,1.064950
5016,2026-09-23,AAPL,Technology,337.019989,341.799988,335.500000,341.079987,31658800,-0.008362,-0.007202,-0.008035,0.013868,0.013830,326.948000,321.406815,1.030806,1.048578
5017,2026-09-23,NVDA,Technology,225.509995,228.949997,224.020004,228.029999,89547300,-0.008362,-0.007202,-0.014681,0.054278,0.028540,221.029596,215.190378,1.020271,1.047956
5018,2026-09-24,AAPL,Technology,335.920013,338.910004,334.299988,336.720001,24733100,-0.000148,-0.000821,-0.003264,-0.003205,0.013820,328.071500,321.580859,1.023923,1.044590
5019,2026-09-24,NVDA,Technology,224.580002,224.940002,221.089996,222.080002,77469900,-0.000148,-0.000821,-0.004124,0.023890,0.028243,221.787313,215.436729,1.012592,1.042441
5020,2026-09-25,AAPL,Technology,341.070007,341.670013,334.529999,336.040009,30002500,0.004588,0.005435,0.015331,0.014697,0.014069,329.396001,321.742802,1.035441,1.060070
5021,2026-09-25,NVDA,Technology,225.070007,226.940002,223.130005,225.130005,89947700,0.004588,0.005435,0.002182,0.012597,0.020290,221.654555,215.794765,1.015409,1.042982
5022,2026-09-28,AAPL,Technology,338.399994,342.989990,338.040009,340.369995,32724700,-0.010705,-0.007441,-0.007828,-0.001711,0.014007,330.331000,321.841754,1.024427,1.051448
5023,2026-09-28,NVDA,Technology,228.860001,233.210007,228.039993,229.750000,141544300,-0.010705,-0.007441,0.016839,0.006509,0.017570,222.232213,216.320299,1.029824,1.057968
5024,2026-09-29,AAPL,Technology,332.345001,337.059998,331.510010,337.059998,12025955,0.000950,-0.002338,-0.017893,-0.021795,0.014541,331.105750,321.962483,1.003743,1.032248
5025,2026-09-29,NVDA,Technology,230.899994,232.820007,229.220001,230.994995,40270708,0.000950,-0.002338,0.008914,0.008870,0.017404,222.750551,216.877243,1.036586,1.064658

# Volume Features

In [10]:
test_data = FE.add_average_volume_feature() #Trading activity - default is 20

test_data = FE.add_relative_volume()

test_data

Price,Date,Ticker,Sector,Close,High,Low,Open,Volume,QQQ_Return,SPY_Return,Daily_Return,Return_5D,Volatility_20D,SMA_20D,SMA_50D,Price_to_SMA_20D,Price_to_SMA_50D,Volume_Average_20D,Relative_Volume_20D
0,2016-09-29,AAPL,Technology,25.653965,26.024437,25.567065,25.878078,143548000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2016-09-29,NVDA,Technology,1.653514,1.658666,1.620394,1.635605,336684000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2016-09-30,AAPL,Technology,25.852909,25.926088,25.567052,25.717984,145516400,0.007468,0.007546,0.007755,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2016-09-30,NVDA,Technology,1.680990,1.697427,1.652778,1.662591,429932000,0.007468,0.007546,0.016617,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2016-10-03,AAPL,Technology,25.731701,25.852906,25.676817,25.775152,86807200,-0.001432,-0.002404,-0.004688,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5021,2026-09-25,NVDA,Technology,225.070007,226.940002,223.130005,225.130005,89947700,0.004588,0.005435,0.002182,0.012597,0.020290,221.654555,215.794765,1.015409,1.042982,1.160675e+08,0.774960
5022,2026-09-28,AAPL,Technology,338.399994,342.989990,338.040009,340.369995,32724700,-0.010705,-0.007441,-0.007828,-0.001711,0.014007,330.331000,321.841754,1.024427,1.051448,4.259910e+07,0.768202
5023,2026-09-28,NVDA,Technology,228.860001,233.210007,228.039993,229.750000,141544300,-0.010705,-0.007441,0.016839,0.006509,0.017570,222.232213,216.320299,1.029824,1.057968,1.133889e+08,1.248308
5024,2026-09-29,AAPL,Technology,332.345001,337.059998,331.510010,337.059998,12025955,0.000950,-0.002338,-0.017893,-0.021795,0.014541,331.105750,321.962483,1.003743,1.032248,4.113826e+07,0.292330
5025,2026-09-29,NVDA,Technology,230.899994,232.820007,229.220001,230.994995,40270708,0.000950,-0.002338,0.008914,0.008870,0.017404,222.750551,216.877243,1.036586,1.064658,1.091673e+08,0.368890

# Target Variable - 5 Day return

In [12]:
test_data = FE.add_target_variable(5)

test_data = test_data.dropna().copy()

FE.data = test_data

FE.save_features()

FE.data

Features data saved for Price       Date Ticker      Sector       Close        High         Low  \
0     2016-09-29   AAPL  Technology   25.653965   26.024437   25.567065
19    2016-09-29   NVDA  Technology    1.653514    1.658666    1.620394
25    2016-09-30   AAPL  Technology   25.852909   25.926088   25.567052
44    2016-09-30   NVDA  Technology    1.680990    1.697427    1.652778
50    2016-10-03   AAPL  Technology   25.731701   25.852906   25.676817
...          ...    ...         ...         ...         ...         ...
62769 2026-09-25   NVDA  Technology  225.070007  226.940002  223.130005
62775 2026-09-28   AAPL  Technology  338.399994  342.989990  338.040009
62794 2026-09-28   NVDA  Technology  228.860001  233.210007  228.039993
62800 2026-09-29   AAPL  Technology  332.345001  337.059998  331.510010
62819 2026-09-29   NVDA  Technology  230.899994  232.820007  229.220001

Price        Open     Volume
0       25.878078  143548000
19       1.635605  336684000
25      25.717984  145516400
44       1.662591  429932000
50      25.775152   86807200
...           ...        ...
62769  225.130005   89947700
62775  340.369995   32724700
62794  229.750000  141544300
62800  337.059998   12025955
62819  230.994995   40270708

[5026 rows x 8 columns].

Price,Date,Ticker,Sector,Close,High,Low,Open,Volume,QQQ_Return,SPY_Return,...,Return_5D,Volatility_20D,SMA_20D,SMA_50D,Price_to_SMA_20D,Price_to_SMA_50D,Volume_Average_20D,Relative_Volume_20D,Future_Return_5D,Target_5D
98,2016-12-08,AAPL,Technology,25.771877,25.843133,25.422489,25.482253,108273200,0.001774,0.002449,...,0.024021,0.012764,25.293078,25.814255,1.018930,0.998358,131367840.0,0.824199,0.033001,1.0
99,2016-12-08,NVDA,Technology,2.296763,2.373912,2.286199,2.338778,381544000,0.001774,0.002449,...,0.066636,0.071426,2.218632,1.894732,1.035216,1.212184,673159800.0,0.566796,0.055948,1.0
100,2016-12-09,AAPL,Technology,26.192514,26.364909,25.815545,25.815545,137610400,0.007843,0.006040,...,0.036851,0.011312,25.363874,25.825026,1.032670,1.014230,126821460.0,1.085072,0.017727,1.0
101,2016-12-09,NVDA,Technology,2.255978,2.316174,2.228706,2.314454,382312000,0.007843,0.006040,...,0.038101,0.071009,2.248302,1.906782,1.003414,1.183134,648811400.0,0.589250,0.093553,1.0
102,2016-12-12,AAPL,Technology,26.043110,26.433871,25.856922,26.040811,105497600,-0.004519,-0.001147,...,0.038402,0.011443,25.419845,25.828830,1.024519,1.008296,125267560.0,0.842178,0.029479,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5001,2026-09-11,NVDA,Technology,218.289993,222.000000,218.149994,221.240005,89060100,0.008734,0.008524,...,-0.043404,0.028009,219.940825,212.356153,0.992494,1.027943,127719035.0,0.697313,0.018233,1.0
5002,2026-09-14,AAPL,Technology,333.079987,335.500000,331.339996,334.790009,39269100,-0.007973,-0.004462,...,0.040973,0.015034,317.983498,318.324693,1.047476,1.046353,43085305.0,0.911427,0.017714,1.0
5003,2026-09-14,NVDA,Technology,210.960007,212.770004,208.929993,211.240005,132267200,-0.007973,-0.004462,...,-0.083191,0.028930,219.243408,212.683109,0.962218,0.991898,130548350.0,1.013166,0.077835,1.0
5004,2026-09-15,AAPL,Technology,331.339996,331.779999,328.350006,330.140015,31748200,-0.006543,-0.004587,...,0.047815,0.015140,319.270998,318.703681,1.037802,1.039649,42764250.0,0.742400,0.025382,1.0
5005,2026-09-15,NVDA,Technology,212.169998,213.940002,211.160004,213.380005,88059700,-0.006543,-0.004587,...,-0.059020,0.028990,218.613983,213.019880,0.970523,0.996010,130267400.0,0.675992,0.078710,1.0