# Feature Engineering

In [1]:
import numpy as np
import pandas as pd
import yfinance as yf
from market_ml.data_loader import DataLoader
import matplotlib.pyplot as plt
import plotly.express as px
from market_ml.config import * 
from market_ml.EDA import * 
from market_ml.feature_engineering import *

# Data Loading

In [2]:
dl = DataLoader(tickers=TICKERS, period="10y", interval="1d")
market_data = dl.load_data()
sectors = market_data["Sector"].unique()

Data loaded for ['AAPL', 'MSFT', 'NVDA', 'META', 'GOOGL', 'JPM', 'GS', 'BAC', 'MS', 'BLK', 'JNJ', 'UNH', 'ABBV', 'PFE', 'MRK', 'XOM', 'CVX', 'COP', 'SLB', 'EOG', 'AMZN', 'COST', 'WMT', 'HD', 'MCD']

In [3]:
#just testing with one stock for now 

test_ticker = ['AAPL', 'NVDA']
test_data = market_data[market_data["Ticker"].isin(test_ticker)].copy()

test_data

Price,Date,Ticker,Sector,Close,High,Low,Open,Volume
0,2016-09-28,AAPL,Technology,26.058723,26.216517,25.939808,25.999266,118564400
19,2016-09-28,NVDA,Technology,1.638303,1.639530,1.617450,1.634869,319788000
25,2016-09-29,AAPL,Technology,25.653952,26.024423,25.567052,25.878064,143548000
44,2016-09-29,NVDA,Technology,1.653514,1.658666,1.620395,1.635605,336684000
50,2016-09-30,AAPL,Technology,25.852915,25.926094,25.567058,25.717989,145516400
...,...,...,...,...,...,...,...,...
62769,2026-09-24,NVDA,Technology,224.580002,224.940002,221.089996,222.080002,77469900
62775,2026-09-25,AAPL,Technology,341.070007,341.670013,334.529999,336.040009,29950100
62794,2026-09-25,NVDA,Technology,225.070007,226.940002,223.130005,225.130005,89808400
62800,2026-09-28,AAPL,Technology,341.239990,342.988007,339.320007,340.369995,11857329
62819,2026-09-28,NVDA,Technology,229.979904,233.210007,228.464996,229.699997,75230198

In [4]:
FE = FeatureEngineer(test_data)

# Returns

In [5]:

test_data = FE.add_daily_returns() #Daily Price Movement 
test_data = FE.add_return_feature() #Very short term momentum - default is 5 days.

# Volatility Features

In [6]:

test_data = FE.add_volatility_feature() #recent variability - default is 20 days

# Trend Features

In [7]:
test_data = FE.add_SMA_feature() #recent price trend - default is 20 
test_data = FE.add_SMA_feature(50) #longer term price trend 
test_data = FE.add_price_relative_to_sma() #position relative to trend - default is 20
test_data = FE.add_price_relative_to_sma(50) #position relative to longer trend 

test_data.tail(20)

Price,Date,Ticker,Sector,Close,High,Low,Open,Volume,Daily_Return,Return_5D,Volatility_20D,SMA_20D,SMA_50D,Price_to_SMA_20D,Price_to_SMA_50D
62575,2026-09-15,AAPL,Technology,331.339996,331.779999,328.350006,330.140015,31748200,-0.005224,0.047815,0.015140,319.270998,318.703681,1.037802,1.039649
62594,2026-09-15,NVDA,Technology,212.169998,213.940002,211.160004,213.380005,88059700,0.005736,-0.059020,0.028990,218.613983,213.019880,0.970523,0.996010
62600,2026-09-16,AAPL,Technology,332.410004,335.480011,330.700012,332.529999,35981000,0.003229,0.054132,0.014942,320.389998,319.144035,1.037517,1.041567
62619,2026-09-16,NVDA,Technology,213.899994,216.759995,212.500000,214.139999,96563600,0.008154,-0.042610,0.028648,218.334263,213.363682,0.979690,1.002514
62625,2026-09-17,AAPL,Technology,337.000000,338.339996,330.179993,334.769989,36700200,0.013808,0.031938,0.014522,321.398499,319.621636,1.048543,1.054372
62644,2026-09-17,NVDA,Technology,219.339996,219.910004,217.149994,218.380005,94191300,0.025432,0.004488,0.029149,218.435421,213.672645,1.004141,1.026524
62650,2026-09-18,AAPL,Technology,336.130005,338.489990,332.529999,337.910004,86588200,-0.002582,0.011617,0.013771,322.639999,320.025286,1.041811,1.050323
62669,2026-09-18,NVDA,Technology,222.270004,222.729996,218.029999,219.350006,190287400,0.013358,0.018233,0.029262,218.718539,214.066978,1.016238,1.038320
62675,2026-09-21,AAPL,Technology,338.980011,339.640015,333.049988,335.279999,34999200,0.008479,0.017714,0.013590,324.121500,320.503920,1.045842,1.057647
62694,2026-09-21,NVDA,Technology,227.380005,228.500000,221.559998,222.940002,109806100,0.022990,0.077835,0.029501,219.363539,214.400094,1.036544,1.060541
62700,2026-09-22,AAPL,Technology,339.750000,345.339996,338.750000,340.140015,40711800,0.002271,0.025382,0.013596,325.592000,320.958188,1.043484,1.058549
62719,2026-09-22,NVDA,Technology,228.869995,229.979996,226.500000,226.850006,95746700,0.006553,0.078710,0.028501,220.394690,214.911444,1.038455,1.064950
62725,2026-09-23,AAPL,Technology,337.019989,341.799988,335.500000,341.079987,31658800,-0.008035,0.013868,0.013830,326.948000,321.406815,1.030806,1.048578
62744,2026-09-23,NVDA,Technology,225.509995,228.949997,224.020004,228.029999,89547300,-0.014681,0.054278,0.028540,221.029596,215.190378,1.020271,1.047956
62750,2026-09-24,AAPL,Technology,335.920013,338.910004,334.299988,336.720001,24733100,-0.003264,-0.003205,0.013820,328.071500,321.580859,1.023923,1.044590
62769,2026-09-24,NVDA,Technology,224.580002,224.940002,221.089996,222.080002,77469900,-0.004124,0.023890,0.028243,221.787313,215.436729,1.012592,1.042441
62775,2026-09-25,AAPL,Technology,341.070007,341.670013,334.529999,336.040009,29950100,0.015331,0.014697,0.014069,329.396001,321.742802,1.035441,1.060070
62794,2026-09-25,NVDA,Technology,225.070007,226.940002,223.130005,225.130005,89808400,0.002182,0.012597,0.020290,221.654555,215.794765,1.015409,1.042982
62800,2026-09-28,AAPL,Technology,341.239990,342.988007,339.320007,340.369995,11857329,0.000498,0.006667,0.013792,330.473000,321.898554,1.032581,1.060086
62819,2026-09-28,NVDA,Technology,229.979904,233.210007,228.464996,229.699997,75230198,0.021815,0.011434,0.017814,222.288208,216.342697,1.034602,1.063035

# Volume Features

In [10]:
test_data = FE.add_average_volume_feature() #Trading activity - default is 20

test_data = FE.add_relative_volume()

test_data

Price,Date,Ticker,Sector,Close,High,Low,Open,Volume,Daily_Return,Return_5D,Volatility_20D,SMA_20D,SMA_50D,Price_to_SMA_20D,Price_to_SMA_50D,Volume_Average_20D,Relative_Volume_20
0,2016-09-28,AAPL,Technology,26.058723,26.216517,25.939808,25.999266,118564400,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,2016-09-28,NVDA,Technology,1.638303,1.639530,1.617450,1.634869,319788000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,2016-09-29,AAPL,Technology,25.653952,26.024423,25.567052,25.878064,143548000,-0.015533,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44,2016-09-29,NVDA,Technology,1.653514,1.658666,1.620395,1.635605,336684000,0.009284,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50,2016-09-30,AAPL,Technology,25.852915,25.926094,25.567058,25.717989,145516400,0.007756,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62769,2026-09-24,NVDA,Technology,224.580002,224.940002,221.089996,222.080002,77469900,-0.004124,0.023890,0.028243,221.787313,215.436729,1.012592,1.042441,1.265156e+08,0.612335
62775,2026-09-25,AAPL,Technology,341.070007,341.670013,334.529999,336.040009,29950100,0.015331,0.014697,0.014069,329.396001,321.742802,1.035441,1.060070,4.289271e+07,0.698256
62794,2026-09-25,NVDA,Technology,225.070007,226.940002,223.130005,225.130005,89808400,0.002182,0.012597,0.020290,221.654555,215.794765,1.015409,1.042982,1.160605e+08,0.773806
62800,2026-09-28,AAPL,Technology,341.239990,342.988007,339.320007,340.369995,11857329,0.000498,0.006667,0.013792,330.473000,321.898554,1.032581,1.060086,4.155311e+07,0.285354
62819,2026-09-28,NVDA,Technology,229.979904,233.210007,228.464996,229.699997,75230198,0.021815,0.011434,0.017814,222.288208,216.342697,1.034602,1.063035,1.100662e+08,0.683499